Homework 05 05 2023
mart8ins/Homework1 pull request #1
Opened 2023-05-07 09:10 UTC by mart8ins

Finished homework - 
* Types and variables
*  Arithmetics

2023-05-07 18:33 UTC, janistumpelis requested changes
Paldies, kopumā ļoti labi 👍 Tikai pāris sīkumi, kuri jāpielbao. Kad pielabosi, tad uzlikšu approve.

2023-05-07 18:33 UTC, janistumpelis commented on src/main/java/io/codelex/arithmetic/practice/Exercise2.java
> +        CheckOddEven(8);
Metožu nosaukumi Javā jāraksta ar mazo burtu.

2023-05-07 18:33 UTC, janistumpelis commented on src/main/java/io/codelex/arithmetic/practice/Exercise4.java
> +    private static void Product1ToN() {
Tas pats par metožu nosaukumiem - jābūt ar mazo burtu.

2023-05-07 18:33 UTC, janistumpelis commented on src/main/java/io/codelex/arithmetic/practice/Exercise6.java
> +    private static void CozaLozaWoza() {
Metodes nosaukums jāraksta ar mazo - vairāk šo nekomentēšu, ja vēl kaut kur ir - pielabo.

2023-05-07 18:33 UTC, janistumpelis commented on src/main/java/io/codelex/arithmetic/practice/Exercise6.java
> +            for (int j = 1; j <= 110; j += 11) {
Vari paskaidrot, kam šis cikls? :)

2023-05-08 05:54 UTC, mart8ins commented on src/main/java/io/codelex/arithmetic/practice/Exercise6.java
> +            for (int j = 1; j <= 110; j += 11) {
Metožu nosaukumus izlaboju. Lielais burts bija tikai tur, kur metožu nosaukumus kopēju pa tiešo no README, nepamaniju šo niansi. Par ciklu - nosacījumā bija minēts, ka jāprintē 11 elementi rindā. Šis ir veids kā es izdomāju sākt jaunu rindu ik pa 11 elementiem.

2023-05-08 06:24 UTC, janistumpelis commented on src/main/java/io/codelex/arithmetic/practice/Exercise6.java
> +            for (int j = 1; j <= 110; j += 11) {
Ok domu sapratu, bet to varētu noteikti izdarīt nedaudz efektīvāk - ja piemēram tas limits būtu nevis 110, bet gan 100000, tad viņam diezgan ilgs laiks paietu šajā otrajā ciklā, lai pārliecinātos, vai nav jāturpina jaunā rindā. 
Varētu pamēģināt ko šādu `if (i % 11 == 0)` :)

2023-05-08 06:42 UTC, mart8ins commented on src/main/java/io/codelex/arithmetic/practice/Exercise6.java
> +            for (int j = 1; j <= 110; j += 11) {
Tiešām 👍 Ņēmu vērā uz izlaboju. Bet izlaboju līdz ekselencei ar i % 11 == 1, jo i % 11 == 0 sanāk, ka printē rindas ik pa 10 elementiem.

2023-05-08 06:50 UTC, janistumpelis approved these changes
Lieku approve, pie pogas, kura paredzēta mērdžošanai nospied bultiņu un izvēlies rebase and merge. Kad tas tiks izdarīts, tad izmaiņas tiks pievienotas main branch (bet pagaidām tikai iekš github). Pēc tam datorā pārslēdzies uz main branch ar `git checout main` un izpildi `git pull` tas jaunākās izmaiņas lejupielādēs no github.

2023-05-08 07:05 UTC, merged